const data = {
  products: [
    {
      _id: 1,
      name: "Headphones",
      category: "Headphones",
      image: "/images/product1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Beats",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
    {
      _id: 2,
      name: "Headphones",
      category: "Headphones",
      image: "/images/product1.jpg",
      price: 120,
      brand: "Beats",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
    {
      _id: 3,
      name: "Headphones",
      category: "Headphones",
      image: "/images/product1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Beats",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
    {
      _id: 4,
      name: "Headphones",
      category: "Headphones",
      image: "/images/product1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Beats",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
  ],
};

export default data;
